package com.skniro.glass_delight.item;

import com.skniro.glass_delight.GlassDelight;
import com.skniro.glass_delight.block.MapleBlocks;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;


public class MapleCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, GlassDelight.MODID);

    public static final Supplier<CreativeModeTab> Maple_Group = CREATIVE_MODE_TABS.register("maple_group",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(Blocks.GLASS))
                    .title(Component.translatable("itemGroup.maple.maple_group"))
                    .displayItems((pParameters, pOutput) -> {
                        pOutput.accept(MapleBlocks.GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.WHITE_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.WHITE_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.WHITE_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.WHITE_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.WHITE_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.WHITE_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.WHITE_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.ORANGE_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.ORANGE_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.ORANGE_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.ORANGE_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.ORANGE_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.ORANGE_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.ORANGE_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.MAGENTA_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.MAGENTA_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.MAGENTA_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.MAGENTA_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.MAGENTA_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.MAGENTA_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.MAGENTA_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.YELLOW_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.YELLOW_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.YELLOW_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.YELLOW_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.YELLOW_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.YELLOW_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.YELLOW_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.LIME_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.LIME_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.LIME_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.LIME_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.LIME_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.LIME_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.LIME_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.PINK_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.PINK_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.PINK_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.PINK_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.PINK_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.PINK_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.PINK_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.GRAY_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.GRAY_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.GRAY_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.GRAY_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.GRAY_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.GRAY_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.GRAY_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.CYAN_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.CYAN_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.CYAN_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.CYAN_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.CYAN_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.CYAN_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.CYAN_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.PURPLE_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.PURPLE_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.PURPLE_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.PURPLE_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.PURPLE_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.PURPLE_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.PURPLE_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.BLUE_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.BLUE_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.BLUE_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.BLUE_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.BLUE_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.BLUE_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.BLUE_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.BROWN_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.BROWN_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.BROWN_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.BROWN_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.BROWN_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.BROWN_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.BROWN_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.GREEN_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.GREEN_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.GREEN_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.GREEN_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.GREEN_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.GREEN_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.GREEN_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.RED_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.RED_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.RED_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.RED_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.RED_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.RED_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.RED_STAINED_GLASS_WALL.get());
                        pOutput.accept(MapleBlocks.BLACK_STAINED_GLASS_SLAB.get());
                        pOutput.accept(MapleBlocks.BLACK_STAINED_GLASS_STAIRS.get());
                        pOutput.accept(MapleBlocks.BLACK_STAINED_GLASS_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.BLACK_STAINED_GLASS_BUTTON.get());
                        pOutput.accept(MapleBlocks.BLACK_STAINED_GLASS_FENCE.get());
                        pOutput.accept(MapleBlocks.BLACK_STAINED_GLASS_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.BLACK_STAINED_GLASS_WALL.get());

                        pOutput.accept(MapleBlocks.WHITE_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.WHITE_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.WHITE_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.WHITE_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.WHITE_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.WHITE_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.WHITE_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.ORANGE_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.ORANGE_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.ORANGE_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.ORANGE_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.ORANGE_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.ORANGE_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.ORANGE_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.MAGENTA_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.MAGENTA_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.MAGENTA_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.MAGENTA_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.MAGENTA_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.MAGENTA_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.MAGENTA_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.LIGHT_BLUE_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.YELLOW_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.YELLOW_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.YELLOW_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.YELLOW_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.YELLOW_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.YELLOW_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.YELLOW_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.LIME_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.LIME_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.LIME_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.LIME_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.LIME_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.LIME_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.LIME_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.PINK_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.PINK_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.PINK_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.PINK_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.PINK_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.PINK_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.PINK_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.GRAY_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.GRAY_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.GRAY_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.GRAY_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.GRAY_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.GRAY_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.GRAY_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.LIGHT_GRAY_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.CYAN_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.CYAN_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.CYAN_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.CYAN_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.CYAN_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.CYAN_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.CYAN_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.PURPLE_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.PURPLE_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.PURPLE_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.PURPLE_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.PURPLE_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.PURPLE_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.PURPLE_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.BLUE_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.BLUE_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.BLUE_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.BLUE_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.BLUE_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.BLUE_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.BLUE_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.BROWN_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.BROWN_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.BROWN_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.BROWN_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.BROWN_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.BROWN_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.BROWN_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.GREEN_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.GREEN_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.GREEN_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.GREEN_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.GREEN_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.GREEN_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.GREEN_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.RED_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.RED_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.RED_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.RED_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.RED_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.RED_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.RED_CONCRETE_WALL.get());
                        pOutput.accept(MapleBlocks.BLACK_CONCRETE_SLAB.get());
                        pOutput.accept(MapleBlocks.BLACK_CONCRETE_STAIRS.get());
                        pOutput.accept(MapleBlocks.BLACK_CONCRETE_PRESSURE_PLATE.get());
                        pOutput.accept(MapleBlocks.BLACK_CONCRETE_BUTTON.get());
                        pOutput.accept(MapleBlocks.BLACK_CONCRETE_FENCE.get());
                        pOutput.accept(MapleBlocks.BLACK_CONCRETE_FENCE_GATE.get());
                        pOutput.accept(MapleBlocks.BLACK_CONCRETE_WALL.get());
                    })
                    .build());


    public static void registerMapleCreativeModeTabs(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
