package com.skniro.glass_delight.datagen;

import com.skniro.glass_delight.block.MapleBlocks;
import com.skniro.glass_delight.block.MapleSignBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.block.CropBlock;
import net.minecraft.item.Items;
import net.minecraft.loot.condition.BlockStatePropertyLootCondition;
import net.minecraft.loot.entry.ItemEntry;
import net.minecraft.loot.function.SetCountLootFunction;
import net.minecraft.loot.provider.number.UniformLootNumberProvider;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;


public class MapleLootTableGenerator extends FabricBlockLootTableProvider {
    public MapleLootTableGenerator(FabricDataOutput dataGenerator, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataGenerator, registryLookup);
    }
    public static final float[] SAPLING_DROP_CHANCE = new float[]{0.048F, 0.0425F, 0.062333336F, 0.1F};

    @Override
    public void generate() {
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.WHITE_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.ORANGE_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.YELLOW_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.LIME_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.PINK_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.GRAY_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.CYAN_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.PURPLE_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.BLUE_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.BROWN_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.GREEN_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.RED_STAINED_GLASS_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_SLAB);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_WALL);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_BUTTON);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_FENCE);
        addDropWithSilkTouch(MapleBlocks.BLACK_STAINED_GLASS_FENCE_GATE);

// 混凝土 Loot Table
        addDropWithSilkTouch(MapleBlocks.WHITE_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.WHITE_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.WHITE_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.WHITE_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.WHITE_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.WHITE_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.WHITE_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.ORANGE_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.ORANGE_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.ORANGE_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.ORANGE_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.ORANGE_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.ORANGE_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.ORANGE_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.MAGENTA_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_BLUE_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.YELLOW_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.YELLOW_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.YELLOW_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.YELLOW_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.YELLOW_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.YELLOW_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.YELLOW_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.LIME_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIME_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIME_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.LIME_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.LIME_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.LIME_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.LIME_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.PINK_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.PINK_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.PINK_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.PINK_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.PINK_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.PINK_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.PINK_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.GRAY_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.GRAY_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.GRAY_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.GRAY_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.GRAY_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.GRAY_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.GRAY_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.LIGHT_GRAY_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.CYAN_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.CYAN_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.CYAN_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.CYAN_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.CYAN_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.CYAN_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.CYAN_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.PURPLE_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.PURPLE_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.PURPLE_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.PURPLE_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.PURPLE_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.PURPLE_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.PURPLE_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.BLUE_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BLUE_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.BLUE_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.BLUE_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.BLUE_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.BLUE_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.BLUE_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.BROWN_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BROWN_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.BROWN_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.BROWN_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.BROWN_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.BROWN_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.BROWN_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.GREEN_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.GREEN_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.GREEN_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.GREEN_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.GREEN_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.GREEN_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.GREEN_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.RED_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.RED_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.RED_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.RED_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.RED_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.RED_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.RED_CONCRETE_FENCE_GATE);
        addDropWithSilkTouch(MapleBlocks.BLACK_CONCRETE_STAIRS);
        addDropWithSilkTouch(MapleBlocks.BLACK_CONCRETE_SLAB);
        addDropWithSilkTouch(MapleBlocks.BLACK_CONCRETE_WALL);
        addDropWithSilkTouch(MapleBlocks.BLACK_CONCRETE_PRESSURE_PLATE);
        addDropWithSilkTouch(MapleBlocks.BLACK_CONCRETE_BUTTON);
        addDropWithSilkTouch(MapleBlocks.BLACK_CONCRETE_FENCE);
        addDropWithSilkTouch(MapleBlocks.BLACK_CONCRETE_FENCE_GATE);
    }
}
